### ISSUE TITLE
Unable to install on Firefox

### ISSUE THREAD

**Issue by hmnd** [SettingDust/obsidian-web-clipper#1]
Hey, thanks for this extension!
I'm trying to install it on Firefox and it seems that the whatever is currently published to [Mozilla Add-ons](https://addons.mozilla.org/en-US/firefox/addon/dust-obsidian-web-clipper/) is corrupted and won't install. See below for a screenshot.
![image](https://user-images.githubusercontent.com/12853597/134451932-44c93632-6de3-4715-8583-13e00aed795e.png)

**Comment by SettingDust** [comment]
[Fixed](https://addons.mozilla.org/en-US/firefox/addon/dust-obsidian-web-clipper/)
